export const ORIGENES_DESTINOS = [
  'Montevideo',
  'Nueva Palmira',
  'Colonia',
  'Fray Bentos',
  'Paysandú',
  'Salto',
  'Rivera',
  'Chuy',
  'Río Branco',
  'Artigas',
  'Bella Unión',
  'Aceguá',
  'Melo',
  'Treinta y Tres',
  'Rocha',
  'Maldonado',
  'Punta del Este',
  'Minas',
  'Florida',
  'Durazno',
  'Tacuarembó',
  'Mercedes',
  'Dolores',
  'Carmelo',
  'Juan Lacaze',
  'Rosario',
  'Young',
  'Trinidad',
  'San José',
  'Canelones',
  'Pando',
  'Las Piedras',
  'Progreso',
  'Santa Lucía',
  'San Carlos',
  'Pan de Azúcar',
  'Piriápolis',
  'Atlántida',
  'La Paloma',
  'La Pedrera',
  'Cabo Polonio',
  'Punta del Diablo',
  'Castillos',
  'Lascano',
  'Cebollatí',
  'Vergara',
  'Nico Pérez',
  'José Pedro Varela',
  'Mariscala',
  'Sarandí del Yi',
  'Paso de los Toros',
  'Cardona',
  'Florencio Sánchez',
  'Ismael Cortinas',
  'Nuevo Berlín',
  'San Javier',
  'Puerto de Nueva Palmira',
  'Puerto de Montevideo',
  'Aeropuerto de Carrasco',
  'Zona Franca Colonia',
  'Zona Franca Nueva Palmira',
  'Parque Industrial Pando',
  'Terminal de Cargas Uruguay',
  'Puerto Sauce',
  'Puerto Fray Bentos'
];

export const DESPACHANTES = [
  'SKUNCA SPINELLI CAROLINA',
  'SCHRAMM CANABAL AGUSTINA',
  'ZUGASTI BARRIO FERNANDO LUIS',
  'QUEROL CAVANI CARLOS RAFAEL',
  'LUIS LAUREIRO',
  'LAMANNA ACEVEDO MARIO NELSON'
];